# fly.toml app configuration file generated for jonlovesbookapp on 2023-12-04T11:46:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jonlovesbookapp"
primary_region = "hkg"

[deploy]
  release_command = "npm run build:fly"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "20.11.0"

[env]
  PORT = "3000" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]



