# fly.toml app configuration file generated for jonlovesbookapp on 2023-12-04T11:46:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jonlovesbookapp"
primary_region = "hkg"


[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "20.11.0"

[env]
  PORT = "3000" 

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
